/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./resources/**/*.blade.php",
        "./resources/**/*.js",
        "./resources/**/*.vue",
    ],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "surface-dim": "#d7dadf",
                "surface-tint": "#0050e2",
                "inverse-surface": "#2d3135",
                "aozora-sky": "#38BDF8",
                "tertiary-fixed-dim": "#ffb4aa",
                "surface-variant": "#dfe3e8",
                "on-tertiary-fixed": "#410001",
                "on-primary-container": "#e2e6ff",
                "primary-container": "#0d59f2",
                "surface": "#f6f9fe",
                "on-secondary-container": "#5f637a",
                "on-surface": "#181c20",
                "error-container": "#ffdad6",
                "on-primary-fixed-variant": "#003cad",
                "surface-container-low": "#f1f4f9",
                "surface-container-high": "#e5e8ed",
                "secondary-container": "#dde1fc",
                "on-primary": "#ffffff",
                "gold-shrine": "#F59E0B",
                "torii-vermilion": "#E83A30",
                "indigo-night": "#0B1021",
                "secondary-fixed-dim": "#c1c5df",
                "tertiary": "#a40009",
                "inverse-primary": "#b5c4ff",
                "on-tertiary-container": "#ffe0dc",
                "surface-container-highest": "#dfe3e8",
                "on-secondary": "#ffffff",
                "surface-bright": "#f6f9fe",
                "on-tertiary": "#ffffff",
                "outline-variant": "#c3c5d8",
                "on-background": "#181c20",
                "on-surface-variant": "#434655",
                "on-error": "#ffffff",
                "tertiary-container": "#c9221d",
                "surface-container": "#ebeef3",
                "inverse-on-surface": "#eef1f6",
                "surface-container-lowest": "#ffffff",
                "on-error-container": "#93000a",
                "secondary-fixed": "#dde1fc",
                "on-tertiary-fixed-variant": "#930007",
                "sakura-tint": "#FDE8E8",
                "secondary": "#595d74",
                "background": "#f6f9fe",
                "tertiary-fixed": "#ffdad5",
                "on-secondary-fixed-variant": "#41465b",
                "primary-fixed-dim": "#b5c4ff",
                "primary-fixed": "#dce1ff",
                "primary": "#0043c0",
                "cloud-white": "#FFFFFF",
                "on-secondary-fixed": "#161b2e",
                "on-primary-fixed": "#00164e",
                "error": "#ba1a1a",
                "outline": "#737687"
            },
            borderRadius: {
                DEFAULT: "0.25rem",
                lg: "0.5rem",
                xl: "0.75rem",
                full: "9999px"
            },
            spacing: {
                "margin-mobile": "1.25rem",
                "space-xs": "0.25rem",
                "space-xl": "2.5rem",
                "space-2xl": "4rem",
                "space-lg": "1.5rem",
                "margin": "3rem",
                "gutter-mobile": "0.875rem",
                "space-sm": "0.5rem",
                "gutter": "1.5rem",
                "space-md": "1rem"
            },
            fontFamily: {
                "headline-lg-mobile": ["Plus Jakarta Sans"],
                "display-hero-mobile": ["Plus Jakarta Sans"],
                "body-sm": ["Be Vietnam Pro"],
                "headline-sm": ["Plus Jakarta Sans"],
                "label-md": ["Space Grotesk"],
                "headline-md": ["Plus Jakarta Sans"],
                "headline-lg": ["Plus Jakarta Sans"],
                "display-hero": ["Plus Jakarta Sans"],
                "body-lg": ["Be Vietnam Pro"],
                "label-badge": ["Space Grotesk"],
                "label-lg": ["Space Grotesk"],
                "body-md": ["Be Vietnam Pro"]
            },
            fontSize: {
                "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "700" }],
                "display-hero-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "800" }],
                "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
                "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
                "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "500" }],
                "headline-md": ["26px", { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "700" }],
                "headline-lg": ["38px", { lineHeight: "46px", letterSpacing: "-0.02em", fontWeight: "700" }],
                "display-hero": ["56px", { lineHeight: "64px", letterSpacing: "-0.03em", fontWeight: "800" }],
                "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
                "label-badge": ["11px", { lineHeight: "14px", letterSpacing: "0.1em", fontWeight: "700" }],
                "label-lg": ["14px", { lineHeight: "18px", letterSpacing: "0.06em", fontWeight: "600" }],
                "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }]
            }
        }
    },
    plugins: [],
};
